spring.application.name=Gonly

spring.datasource.url=jdbc:postgresql://localhost:5432/gonly_db
spring.datasource.username=postgres
spring.datasource.password=0000

spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=mySuperSecretKeyThatIsAtLeast32CharactersLong9365543845
